[package]
name = "flupp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.32"
thiserror = "1.0.40"
time = "0.3.21"

[dev-dependencies]
insta = "=1.29.0"
